# In _config.yml
title: Cálculo Vectorial
subtitle: Un libro de texto interactivo
description: Un libro de texto interactivo para el curso de Cálculo Vectorial
author: Marco Julio Cañas Campillo
logo: logo.png
execute:
  execute_notebooks: force

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib